public/CHANGELOG.md
src/features/handy/api/handy.ts
src/features/handy/utils/getStrokeSpeedAndDistance.test.ts
src/features/handy/utils/getStrokeSpeedAndDistance.ts

Add support for handy stroke zones

---

src/game/xstate/api/fetchRedditPics.ts

Fix reddit fetching

---

src/stores/currentUser.ts

Fix profile query

---

src/__mocks__/store.ts
src/configureStore.ts
src/features/game-config/components/Form/EdgingStep/components/EdgeFrequencyField.tsx
src/game/xstate/machines/actionMachine.ts

Adjust edge frequency

---

src/features/search/components/GamesTable.tsx

Fix game search sorting

---

src/game/xstate/machines/mediaMachine.ts

Temporary fix to prevent NaN for limit on fetching subreddits

---

src/providers/ProfileProvider.tsx

Add content type to axios wrapper.

---

src/utils/balanceArray.ts

Add unbalancedArray to the balance array function exception.

---

src/game/engine/audio.ts

Add error to failed audio download.

---

src/features/game-config/components/Form/OrgasmStep/OrgasmStep.tsx
src/utils/__tests__/balanceArray.test.ts

Remove rounding from probability diff.

---

src/game/engine/audio.ts

Eat audio file download exception.

---

src/config/setupSentry.ts

Decrease sample rate and only trace errors from site

---

src/game/engine/audio.ts

Add context guard before decoding URL audio files

---

src/utils/__tests__/balanceArray.test.ts
src/utils/balanceArray.ts

Skip completed indexes and recalculate adjustment splits.

---

src/components/Elements/Quote/Quote.stories.tsx
src/components/Elements/Quote/Quote.tsx
src/components/Elements/Quote/index.ts

feat: add quote component

---

src/features/file-system/utils/local-media.ts

fix: shuffle local media files

---

src/features/end/routes/End.tsx

Added 2 buttons in the ending screen: 
1. **Copy to Clipboard**: copies all your links of your bookmarks into your device's clipboard
2. **Save text file**: downloads a txt file to your device with all the bookmarks.

Added Copy to clipboard and Save text file of the bookmarks.

---

src/features/game-config/components/Form/PostOrgasmTortureStep/components/PostOrgasmTortureDurationField.tsx

Fixes typo in form label

---

README.md
docs/game-guide.md
docs/quick-start.md

This PR removes some TODOs from the docs and clarifies some stuff. Just look at the changed files, it's easy to understand since it's only some Markdown
- [x ] Documentation Update (if none of the other choices apply)
- [x ] I have added necessary documentation (if appropriate)
*Insert super funny joke*

doc: Additions and removed TODOs

---

public/index.html

feat: add analytics
